AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False # not included FC layers
EPOCHS: 1   # for testing
CLASSES: 2   # normal, tumor
WEIGHTS: imagenet
LEARNING_RATE: 0.001